### ISSUE TITLE
--no_resample + .raw = pipe error

### ISSUE THREAD

**Issue by bradriley** [oyvindln/ld-decode#101]
Signed 16-bit input with DdD's default .raw extension immediately returns a pipe error if paired with `--no_resample`. 

Not sure if directly related:
Despite being 40 -> 40 MSPS, `--no_resample` consistently runs a little faster than default options.

Example trimmed .raw file: [casper2pana1F.raw.zip](https://github.com/oyvindln/vhs-decode/files/12109177/casper2pana1F.raw.zip)

```
brad@mini ddd % vhs-decode --no_resample casper2pana1F.raw error
fd:: Invalid data found when processing input
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/vhsdecode/process.py", line 212, in build_json
    black = jout["videoParameters"]["black16bIre"]
            ~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Cannot build json: 'NoneType' object is not subscriptable
saving JSON and exiting
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/vhsdecode/process.py", line 212, in build_json
    black = jout["videoParameters"]["black16bIre"]
            ~~~~^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Cannot build json: 'NoneType' object is not subscriptable
```

Two workarounds:

1. Don't use no_resample.
```
brad@mini ddd % vhs-decode casper2pana1F.raw workaround1
Phase previously set: 0
phase0 mean: 5661.34
phase1 mean: 374.79
assumed_phase: 1
saving JSON and exiting #None Unknown
```

2. Rename to .s16.
```
brad@mini ddd % mv casper2pana1F.raw casper2pana1F.s16
brad@mini ddd % vhs-decode --no_resample casper2pana1F.s16 workaround2
Phase previously set: 0
phase0 mean: 5661.34
phase1 mean: 374.79
assumed_phase: 1
saving JSON and exiting #None Unknown     
```                    

(Note: every run above actually included a Numba Deprecation warning, which I deleted from the paste and filed separately as issue #100.)

**Comment by Inky1003** [comment]
The files are not meant to be named just ".raw", but after their sample formats. If It's unsigned 8 bit, then ".u8". If unsigned 16 bits samples, then ".u16". Try to do that.
