### ISSUE TITLE
cvbs-decode vhsdecode.sync Error

### ISSUE THREAD

**Issue by aldude999** [oyvindln/ld-decode#138]
### Bug Description
Running cvbs-decode produces the following output

```
Traceback (most recent call last):
  File "/home/alex/Projects/vhs-decode/vhs-decode/Home_Movies_Alexander_9_4_94/../cvbs-decode", line 2, in <module>
    from cvbsdecode.main import main
  File "/home/alex/Projects/vhs-decode/vhs-decode/cvbsdecode/main.py", line 9, in <module>
    from cvbsdecode.process import CVBSDecode
  File "/home/alex/Projects/vhs-decode/vhs-decode/cvbsdecode/process.py", line 14, in <module>
    import vhsdecode.sync as sync
ModuleNotFoundError: No module named 'vhsdecode.sync'

```

### Steps to Reproduce

1. Install vhs-decode using the instructions in the README.md
2. Create a capture of a composite input using a cxadc card
3. Run:  ../cvbs-decode --debug --ntsc -A --cxadc Test_COMPOSITE.u8 composite-test

### Expected Behaviour

cvbs-decode properly decodes a file

### Environment

- Decode version: [d43225a](https://github.com/oyvindln/vhs-decode/commit/d43225a1d10caa6df94704e24f05eb8aae7d1f20)
- Operating System: Ubuntu 22.04.4 LTS

### Is it related to tbc-video-export?
No

**Comment by aldude999** [comment]
It appears I can workaround this issue by adding:
```
import pyximport
pyximport.install()
```

near the top of cvbsdecode/process.py

**Comment by oyvindln** [comment]
The steps in the readme don't cover running the python modules from the git folder directly, it should work if you run the installed python binaries. If you want to run from the folder you have to run ```python setup.py build_ext --inplace``` in the vhs-decode folder to build the cython extension modules.

The lines you added in the last commend does the same thing when script is ran. It's currently done in vhs-decode but could add that to cvbs.decode as well

**Comment by aldude999** [comment]
I think this section might need to be updated then:
https://github.com/oyvindln/vhs-decode/wiki/Command-List#cvbs-composite-decode

**Example Usage Command:**

`./cvbs-decode --debug --pal -A --cxadc composite-test.u8 composite-test`
